### ISSUE TITLE
errors when loading object

### ISSUE THREAD

**Issue by porres** [iainctduncan/scheme-for-pd#11]
testing release candidate 1 I get this and can't make it stop. Need clear documentation

<img width="899" alt="Screen Shot 2021-10-03 at 18 44 21" src="https://user-images.githubusercontent.com/5360142/135772538-997ec377-b614-4815-8927-9ea2450b2532.png">

**Comment by iainctduncan** [comment]
Can you try adding s4pd/scm (not just s4pd) to your path and tell me if that does it? the object needs to find the scm files, which when you check out the code, are in the "scm" directory of the proejct. I mention this in the Readme, but if it's not adequately clear I can certainly improve it!

**Comment by iainctduncan** [comment]
In the screenshot here, you can see my file preferences have the path where the scm files live added, which depends on where you checked out and built the code: 

<img width="999" alt="Screen Shot 2021-10-03 at 3 11 51 PM" src="https://user-images.githubusercontent.com/3385148/135773112-8ae37832-b64e-47e7-85e6-3806b16b9332.png">

**Comment by porres** [comment]
I just downloaded the mac zipped release, which unpacks to a 's4pd' folder, which I moved to externals.

this folder has no 'scm' subfolder (so there's nothing in it) - so yeah, this is confusing.

The help file also just says "The s4pd object takes 2 optional arguments, an integer for number of outlets, and a filename to load, searching the Pd filepath."

for the "Pd filpath" I understand it is the same folder the opened patch lives and the ones in Pd's added user search paths and the one in declare, so yeah, it's confusing, and it's also how pd objects usually work - so I suggest you do it like that, or is it something you can't really do?

**Comment by iainctduncan** [comment]
Ah ok I see how we have wires crossed, I thought you were building from source. The readme says it's ready for building from source and you are using a pre-release, which I have not advertised as ready, so yes, it's not package ready. The directions are for building from source, and the users who have tried it out so far have been doing that. I will try to attend to these soon and let you know so that we can test the package. I really don't have experience with Pd packaging. 

Thanks for the bug reports!

**Comment by porres** [comment]
did you put the download as it is? cause there's no 'smc' folder...

I also did compile it myself and the result is a just a folder, with no subfolders, and all files just in it.

So in both cases it seems you need to manually alter things, and that's bad. I did what you said manually, I created the subfolder, I put all the files there, I added the extra subfolder to the preferences path, but that just seems like a bad idea/process.

But what seems bad is that you have hardcoded things like that, which is not really intuitive and "pd-like".

It makes sense to me to have the smc files that [s4pd] needs to instanciate (those would be s4pd.scm and s4pd-schedule.scm, right?) in the same folder as the external, and then it just looks for these two there. This would actually be one default folder that pd generally looks for files and you could also hardcode it in the object -  so no need for a 'smc' subfolder and also setting it up in the preferences, that seems like unnecessarily complicated.

Moreover, if you have a patch somewhere and you want to load files, it'd be good if the user could have more flexibility where to put them. Looking for it in the same folder as the patch is saved or wherever in the preferences paths is what's reasonable to me. 

One can have a subfolder in the same folder of the patch called 'smc' or whatever and call files there by simply giving it a 'smcc/' prefix, this is what all externals I know do. I don't see why you'd have to make it differently.

Anyway, I hope you get what I mean.

cheers

**Comment by iainctduncan** [comment]
fixed in src, will update ticket when fixed in release candidate and help updated

**Comment by porres** [comment]
you can use 'c_externdir' from m_imp.h to get the external directory, see https://github.com/porres/pd-cyclone/blob/master/cyclone_objects/binaries/cyclone_lib.c#L640

**Comment by iainctduncan** [comment]
that sounds promising, I'll try that. If it works, I can have it check for core scm files in user defined paths and fall back to the location of the external. thanks for the tip!

**Comment by porres** [comment]
> I can have it check for core scm files in user defined paths and fall back to the location of the external.

but isn't s4pd.scm and s4pd-schedule.scm always in the location of the external? Isn't that how you're packaging it? Why not make it look there first? They're needed every time you create the external, right?

**Comment by iainctduncan** [comment]
closing, satisfied with how this is working now.
