### ISSUE TITLE
build.sh does not work

### ISSUE THREAD

**Issue by umlaeute** [iainctduncan/scheme-for-pd#6]
the `build.sh` is tailored to *your* specific development machine.
it doesn't work anywhere else.

- it assumes that you don't want to have another instance of Pd running while building sc4pd (else: why would you kill pd?)
- it assumes that Pd is version *0.51-1* (the current version of Pd is *0.51-4*; on my macOS system i have installed Pd *0.50-2* or so)
- it assumes that Pd is installed in `/Applications/` (on my system it is installed in `/usr/`
- it assumes that you have a `patchers/s4pd-test.pd` file

now that is all totally fine to help you with your specific workflow. i have ton's of such scriptlets on my harddisk.
but i think it probably shouldn't be submitted to the repository (just like you omitted `patchers/s4pd-test.pd` - most likely for good).
the alternative would be to make the script more generic (e.g. detect which Pd the pd-lib-builder Makefile uses; and use that to launch Pd...) - but i think this is rather an overkill.

**Comment by iainctduncan** [comment]
yeah, it was just my working thing. I've added it to gitignore now.
