### ISSUE TITLE
license file

### ISSUE THREAD

**Issue by danomatika** [iainctduncan/scheme-for-pd#7]
The readme states that "Scheme for Pd and s7 are open source under the BSD license." but I would suggest including a copy of the particular BSD license version as a LICENSE.txt file as well. This makes it unambiguous as there are several different versions of the "BSD license" ie. an extra clause, etc.

Also, I suggest adding attribution and info about licensing in there appropriate places, ie. s4pd.c.

I bring this up mainly as I'm thinking of trying this external out on iOS in [PdParty](http://danomatika.com/code/pdparty) and licensing needs to be relatively upfront for the App Store.

**Comment by iainctduncan** [comment]
thanks, added BSD New

**Comment by danomatika** [comment]
Thanks
